version: '3.9'

services:
  old:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/genych/php82:latest
    volumes:
      - ./first:/www
      - shr:/tmp
    working_dir: /www
    environment:
      - XDEBUG_MODE=debug,profile

  new:
    image: php:8.3.0RC6-fpm-bullseye
    volumes:
      - ./second:/www
    working_dir: /www

  grind:
    image: jokkedk/webgrind:latest
    volumes:
      - shr:/tmp

  nginx:
    image: nginx:latest
    volumes:
      - .nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

volumes:
  shr:
